[[language]]
name = "typescript"
auto-format = false
language-servers = [
  "biome",
  # { name = "typescript-language-server", except-features = [
  #   "format",
  # ] },
  "deno-lsp",
]

# ---- Tsx ---- #
[[language]]
name = "tsx"
roots = ["deno.json", "deno.jsonc"]
auto-format = false
formatter = { command = "biome", args = [
  "check",
  "--fix",
  "--config-path",
  "/home/othman/.config/biome.jsonc",
  "--stdin-file-path=file.tsx",
] }
language-servers = [
  # { name = "typescript-language-server", except-features = [
  #   "format",
  # ] },
  "vscode-html-language-server",
  "superhtml",
  "biome",
  "deno-lsp",
  "scls",
]
